sonar.projectKey=SanttySala03_ItinerariosAeropuertos2026-1
sonar.organization=santtysala
sonar.projectName=ItinerariosAeropuertos2026-1
sonar.projectVersion=2.0.0
sonar.sources=airport_service,itinerary_service,frontend
sonar.exclusions=**/__pycache__/**,**/*.pyc,**/tests/**,**/*.db
sonar.python.version=3.9
sonar.language=py